Lidar_front_end:
   lidar_type: 1   # 1 for Livox-avia, 3 for Ouster-OS1-64
   N_SCANS: 6
   using_raw_point: 1
   point_step: 1
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 0            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 0        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 0            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 800     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]

r3live_vio:
   image_width: 1600
   image_height: 1200
   camera_intrinsic:
      [1786.613933, 0.0, 750.353020,
       0.0, 1787.779541, 595.078266,
       0.0, 0.0, 1.0 ] 
   camera_dist_coeffs: [-0.041809, 0.136929, 0.000474, -0.000807, 0.000000]  #k1, k2, p1, p2, k3
   # Fine extrinsic value. form camera-LiDAR calibration.
   camera_ext_R:
         [ -0.00443849,-0.00925293, 0.99994734,
            0.99998707, 0.00244163, 0.00446126,
           -0.00248278, 0.99995421, 0.00924197 ]
   camera_ext_t: [0.05794244, 0.02363634, 0.04225306]

   # Rough extrinsic value, form CAD model, is not correct enough, but can be online calibrated in our datasets.
   # camera_ext_R:
   #    [0, 0, 1,
   #     -1, 0, 0,
   #     0, -1, 0]
   # camera_ext_t: [0,0,0] 
   
r3live_lio:        
   lio_update_point_step: 4   # Point step used for LIO update.  
   max_iteration: 2           # Maximum times of LIO esikf.
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.30   
   filter_size_surf: 0.30
   filter_size_surf_z: 0.30
   filter_size_map: 0.30

# camera matrix
# 1786.613933 0.000000 750.353020
# 0.000000 1787.878861 595.078266
# 0.000000 0.000000 1.000000

# distortion
# -0.041809 0.136929 0.000474 -0.000807 0.000000

# rectification
# 1.000000 0.000000 0.000000
# 0.000000 1.000000 0.000000
# 0.000000 0.000000 1.000000

# projection
# 1786.859863 0.000000 749.736329 0.000000
# 0.000000 1787.779541 595.104368 0.000000
# 0.000000 0.000000 1.000000 0.000000